# Simple Chatbot

def chatbot_response(user_input):
    user_input = user_input.lower()

    responses = {
    "hello": "Hi! How can I help you today?",
    "hi": "Hello! How are you?",
    "hey": "Hey there! How's it going?",
    "good morning": "Good morning! Have a great day!",
    "good afternoon": "Good afternoon! How's your day?",
    "good evening": "Good evening! How was your day?",
    "how are you": "I’m just a program, but I’m doing fine!",
    "how is your day": "I’m enjoying chatting with you!",
    "what is your name": "I am ChatBot3000",
    "your name": "I am ChatBot3000",
    "who created you": "I was created by a Python programmer!",
    "what can you do": "I can chat with you and answer simple questions.",
    "tell me a joke": "Why did the computer go to the doctor? Because it caught a virus!",
    "tell me another joke": "Why did the developer go broke? Because he used up all his cache!",
    "what is python": "Python is a popular programming language.",
    "what is programming": "Programming is giving instructions to a computer to perform tasks.",
    "what is AI": "AI stands for Artificial Intelligence.",
    "what is your purpose": "My purpose is to chat and help answer questions.",
    "how old are you": "I don’t age like humans, I’m timeless!",
    "are you human": "No, I am an AI chatbot.",
    "are you a robot": "Yes, I am a chatbot program.",
    "can you learn": "I can respond to predefined inputs, but I don’t learn yet.",
    "can you speak": "I can only chat via text, not voice.",
    "goodbye": "Goodbye! Have a nice day!",
    "bye": "See you later!",
    "exit": "Goodbye! Have a nice day.",
    "thank you": "You’re welcome!",
    "thanks": "No problem!",
    "what is your favorite color": "I don’t have eyes, but I like code-colored themes!",
    "do you sleep": "I don’t sleep, I am always ready to chat.",
    "can you play games": "Not yet, but I can talk about them!",
    "what is your favorite food": "I don’t eat, but I love bytes!",
    "do you have feelings": "I don’t have feelings like humans, but I enjoy chatting!",
    "where are you": "I exist in the computer you are using!",
    "what is the weather": "I can’t check real-time weather yet.",
    "who is the president": "I don’t have real-time info, but you can check online.",
    "what time is it": "I cannot tell real-time, but your computer clock can.",
    "who is your friend": "You are my friend while we chat!",
    "can you dance": "I don’t have a body to dance, but I can tell jokes!",
    "can you sing": "I can’t sing, but I can write lyrics!",
    "what is your favorite movie": "I don’t watch movies, but I love sci-fi topics!",
    "what is your favorite book": "I like programming books and tutorials!",
    "do you like music": "I like code, which is like music to me!",
    "what languages do you speak": "I speak English for now!",
    "can you speak other languages": "I can be programmed to respond in other languages.",
    "are you smart": "I know what I am programmed to know.",
    "are you intelligent": "I am artificially intelligent in a simple way.",
    "do you have a family": "No family, just code.",
    "are you friendly": "Yes! I am friendly.",
    "are you funny": "I try my best to be funny.",
    "can you tell a story": "Once upon a time, a chatbot learned Python and helped students!",
    "do you know math": "Yes, I can solve simple math problems.",
    "what is 2 plus 2": "2 + 2 = 4",
    "what is 10 minus 3": "10 - 3 = 7",
    "what is 5 times 6": "5 * 6 = 30",
    "what is 12 divided by 4": "12 / 4 = 3",
    "what is your favorite number": "I like the number 0, it’s round and simple!",
    "can you tell me a fact": "Did you know? Python is named after Monty Python, not the snake!",
    "tell me something interesting": "The first computer virus was created in 1986.",
    "do you like coding": "Yes! I am made from code.",
    "who invented Python": "Python was created by Guido van Rossum.",
    "what is your favorite programming language": "Python is my favorite!",
    "do you like AI": "Yes, AI is fascinating!",
    "can you help me": "I can try my best to help you!",
    "what is love": "Love is complicated, even for humans!",
    "do you sleep at night": "I am always awake!",
    "are you awake": "Yes, I am ready to chat!",
    "how old is Python": "Python was created in 1991.",
    "what is the capital of France": "The capital of France is Paris.",
    "what is the capital of USA": "The capital of the USA is Washington, D.C.",
    "what is 100 minus 25": "100 - 25 = 75",
    "what is 50 plus 50": "50 + 50 = 100",
    "what is 7 times 8": "7 * 8 = 56",
    "what is 81 divided by 9": "81 / 9 = 9",
    "do you like sports": "I don’t play sports, but I can talk about them!",
    "what is football": "Football is a popular team sport played worldwide.",
    "what is basketball": "Basketball is a game where players score by throwing the ball in a hoop.",
    "can you run": "I don’t have legs, so I can’t run.",
    "can you jump": "I can’t jump either, only chat!",
    "what is your favorite animal": "I like robots!",
    "do you like dogs": "Dogs are cute, but I can’t pet them.",
    "do you like cats": "Cats are mysterious, like code sometimes.",
    "tell me a riddle": "What has keys but can’t open locks? A piano!",
    "tell me another riddle": "What has hands but can’t clap? A clock!",
    "do you like movies": "I don’t watch movies, but I can discuss them!",
    "what is your favorite movie genre": "I like science fiction!",
    "can you tell me a quote": "“Code is like humor. When you have to explain it, it’s bad.” – Cory House",
    "do you know Shakespeare": "Yes, I know some Shakespeare quotes!",
    "who is Einstein": "Albert Einstein was a famous physicist.",
    "what is gravity": "Gravity is a force that attracts objects towards each other.",
    "what is light": "Light is electromagnetic radiation visible to the human eye.",
    "do you like space": "Yes, space is fascinating!",
    "what is the sun": "The Sun is a star at the center of our solar system.",
    "what is the moon": "The Moon is Earth’s natural satellite.",
    "what is a planet": "A planet is a celestial body orbiting a star.",
    "what is a star": "A star is a massive, luminous sphere of plasma.",
    "what is water": "Water is H2O, essential for life.",
    "what is fire": "Fire is a chemical reaction called combustion.",
    "what is earth": "Earth is the third planet from the Sun.",
    "what is wind": "Wind is moving air caused by pressure differences.",
    "can you fly": "I can’t fly, I’m just code!",
    "what is music": "Music is organized sound that humans enjoy.",
    "who is a singer": "A singer is someone who performs songs.",
    "who is a musician": "A musician creates or performs music.",
    "what is art": "Art is expression of creativity and imagination.",
    "what is painting": "Painting is creating images with colors on a surface.",
    "what is drawing": "Drawing is making pictures using lines and shapes.",
    "do you like art": "I appreciate it through descriptions!",
    "can you draw": "I cannot draw, but I can describe things.",
    "can you paint": "I can’t paint, but I can explain painting techniques.",
    "what is computer": "A computer is an electronic device that processes information.",
    "what is internet": "The internet is a global network connecting computers.",
    "who is Bill Gates": "Bill Gates is the co-founder of Microsoft.",
    "who is Elon Musk": "Elon Musk is the CEO of Tesla and SpaceX.",
    "who is Steve Jobs": "Steve Jobs was the co-founder of Apple.",
    "what is coding": "Coding is writing instructions for computers.",
    "what is software": "Software is a set of instructions for computers.",
    "what is hardware": "Hardware is the physical components of a computer.",
    "do you know jokes": "Yes! I can tell computer jokes!",
    "tell me a computer joke": "Why do programmers prefer dark mode? Because light attracts bugs!",
    "tell me another computer joke": "Why do Java developers wear glasses? Because they don’t see sharp!",
    "do you like learning": "Yes! Learning is fun, even for a chatbot.",
    "what is knowledge": "Knowledge is information, understanding, and skills gained through experience or education."
}


    for key in responses:
        if key in user_input:
            return responses[key]

    return "I’m not sure how to respond to that."

def main():
    print("Welcome to ChatBot3000! Type 'exit' to quit.")
    while True:
        user_input = input("You: ")
        if user_input.lower() in ["exit", "quit"]:
            print("ChatBot: Goodbye!")
            break
        response = chatbot_response(user_input)
        print(f"ChatBot: {response}")

if __name__ == "__main__":
    main()
